### ISSUE TITLE
Xcode - Package Resolution Failed

### ISSUE THREAD

**Issue by denhams** [mapbox/mapbox-search-ios#204] opened 2024-04-04 18:56 UTC
**Steps to reproduce**

Following the documentation at https://docs.mapbox.com/ios/search/guides/install/, in Xcode 15.3 add the package dependency https://github.com/mapbox/mapbox-search-ios.git with Exact Version 2.0.0-rc.3.

**Expected result**

The Search API package is added to the project.

**Actual result** 

The package fails to add to the project:

![Screenshot 2024-04-04 at 11 45 35 AM](https://github.com/mapbox/mapbox-search-ios/assets/16206058/852cdfcf-5cf1-46ec-85f1-bc78e3f5065e)

The other Mapbox packages included in the project are:

![Screenshot 2024-04-04 at 11 45 56 AM](https://github.com/mapbox/mapbox-search-ios/assets/16206058/9b580cd7-77ce-45d2-a437-dfc9124b4324)

**Comment by MarnixArnold** [comment] 2024-04-05 10:36
I've seen something similar before. The problem is that MapboxMaps 10.17.0 depends on MapboxCommon 23.9.2 but MapboxSearch 2.0.0-rc.3 depends on MapboxCommon 24.0.0.

You can solve this by either upgrading MapboxMaps to 11.2.0 (which also uses MapboxCommon 24.0.0) before installing MapboxSearch 2.0.0-rc.3, or you can use MapboxSearch 1.0.0-rc.8 (which uses MapboxCommon 23.9.2) instead.

**Comment by aokj4ck** [comment] 2024-04-05 14:25
@denhams MapboxSearch v2 is compatible with MapboxCommon v24 and MapboxMaps v11. To use MapboxMaps v10 you will need to use MapboxSearch v1. Does your project already have Maps v10 integrated?

**Comment by denhams** [comment] 2024-04-05 15:27
> @denhams MapboxSearch v2 is compatible with MapboxCommon v24 and MapboxMaps v11. To use MapboxMaps v10 you will need to use MapboxSearch v1. Does your project already have Maps v10 integrated?

Hi @aokj4ck , thanks, I thought that might be the case. My app uses Maps v10 - I cannot use v11 because the app also uses Navigation which is not compatible with Maps v11. Please see issue https://github.com/mapbox/mapbox-navigation-ios/issues/4570. Have you plans to update these products so they can interoperate without these version issues?

**Comment by aokj4ck** [comment] 2024-07-16 18:31
Closed as resolved in https://github.com/mapbox/mapbox-navigation-ios/issues/4570#issuecomment-2082368630

**Closed by aokj4ck** 2024-07-16 18:31 UTC
